name: Build and Deploy Doc
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build doc
        run: |
          sudo apt install -y libgirepository1.0-dev
          pip install -r requirements.txt
          git clone --depth=1 https://github.com/analogdevicesinc/linux.git
          git clone --depth=1 https://github.com/analogdevicesinc/hdl.git
          cd docs/tools
          python process_devicetree_doc.py
          python find_hdl_platforms.py
          cd ../..
          make -C docs html

  deploy_dev:
    name: Deploy master docs
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build doc
        run: |
          sudo apt install -y libgirepository1.0-dev
          pip install -r requirements.txt
          # git clone --depth=1 https://github.com/analogdevicesinc/linux.git
          # git clone --depth=1 https://github.com/analogdevicesinc/hdl.git
          # git clone --depth=1 https://github.com/analogdevicesinc/no-os.git
          # cd docs/tools
          # python process_devicetree_doc.py
          # python find_hdl_platforms.py
          # cd ../..
          pip install .
          vger linux -c
          vger hdl -c
          vger no-os -c
          make -C docs html

      - name: Publish doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html

  # deploy:
  #   name: Deploy docs
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8

  #     - name: Build Doc
  #       run: |
  #        pip install -r requirements/requirements_doc.txt
  #        python setup.py install
  #        mkdocs build -v

  #     - name: Publish doc
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./site